export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_PENDING = " CREATE_JOB_PENDING";
export const CREATE_JOB_SUCCESS = " CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = " CREATE_JOB_ERROR";

export const GET_JOBS_PENDING = " GET_JOBS_PENDING";
export const GET_JOBS_SUCCESS = " GET_JOBS_SUCCESS";
